---
title: "Conserved I-graph"
author: "Ellen Dimmen Chapple"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    number_sections: true
    toc_float: true
    theme: lumen
editor_options:
  chunk_output_type: console
---


```{r}

library(tidyverse)
library(igraph)
library(ggpattern)

```

# Co-expressed genes and angiosperm-specific OGs


```{r}
# Read in expressologs
expressologs <- read.delim("Data/DATA/textFiles/all_expressed_genes.txt", sep = " ") %>%   
  filter(MaxpVal < 0.8)
  

expressologs_2 <- read.delim("Data/DATA/textFiles/all_expressed_genes.txt", sep = " ") %>% 
  filter(MaxpVal < 0.1)

cat("Orthogroups with at least one expressed pair:", expressologs %>% distinct(OrthologGroup) %>% nrow(), "\n")
cat("Orthogroups with at least one co-expressolog:", expressologs_2 %>% distinct(OrthologGroup) %>% nrow(), "\n")




```



```{r}

# Need the ones_and_zeros_all-file to use as a template for finding the ortholog groups specific for angiosperms.
load("Data/DATA/ones_and_zeros_all.RData")

df_with_sums <- ones_and_zeros_all %>%
  mutate(Angiosperms = rowSums(. [1:3])) %>%
  mutate(Cross = rowSums(. [4:12]))%>%
  mutate(Gymnosperms = rowSums(. [13:15])) %>%
  mutate(Conserved = rowSums(. [1:15]))

# Now we want to select only the ortholog groups with an angiosperms sum of 3, while the others two groups are 0.
conserved_ogs_angio <- df_with_sums %>%
  filter(Angiosperms >=2 & Gymnosperms == 0 & Cross == 0) 
 

cat("Number of angiosperm-specific ortholog groups that have at least one expressed (not p-value cutoff) gene pair for all 3 pairs: ", nrow(conserved_ogs_angio))


conserved_ogs_angio <- conserved_ogs_angio %>% 
  filter(rownames(conserved_ogs_angio) %in% expressologs$OrthologGroup)


angio_spec_OG <- rownames(conserved_ogs_angio)


length(angio_spec_OG)

```

#  Finding cliques based on weight of edges

```{r }

# First - find all ortholog groups with at least one clique that involves only 3 species.
expressologs_from_max_cliques <- c()
max_clique_ortholog_groups <- c()
uuc_genes <- c()

for (g in angio_spec_OG) {

   # g <- "OG0000033"
  
  expressologs_g <- expressologs %>% 
    filter(OrthologGroup == g) %>%
    mutate(UGeneSpecies1 = paste0(Species1, "-", GeneSpecies1),
           UGeneSpecies2 = paste0(Species2, "-", GeneSpecies2))
  
  nodes <- data.frame(name = unique(c(expressologs_g$UGeneSpecies1, expressologs_g$UGeneSpecies2)))
  
  edges <- data.frame(from = expressologs_g$UGeneSpecies1, 
                      to = expressologs_g$UGeneSpecies2,  weight = -log(expressologs_g$MaxpVal))
  
  # 
  net <- graph_from_data_frame(edges, directed = FALSE, vertices = nodes)
  
  
  max_clique <- largest_weighted_cliques(net)
  # Finds all of the maximal weighted cliques. 
  
print(g)

  for( c in 1:length(max_clique)){
    
    # c <-1
    clique <- max_clique[[c]]
    clique <- attr(clique, "names")
    
    clique_species <- unique(str_split_fixed(clique, "-", n = 2)[,1])
    clique_genes <-  str_split_fixed(clique, "-", n = 2)[,2]

    
     #
    if(length(clique_species) == 3 ) {
      
      max_clique_ortholog_groups <- c(max_clique_ortholog_groups, g)
      expressologs_in_clique <- expressologs_g %>%
        filter(UGeneSpecies1 %in% clique & UGeneSpecies2 %in% clique) %>% 
        mutate(cliqueSum = sum(MaxpVal))
      
      expressologs_from_max_cliques <- rbind(expressologs_from_max_cliques, expressologs_in_clique)
      
      uuc_genes <- rbind(uuc_genes, data.frame(
      Orthogroup = rep(g, length(clique_genes)),
      Genes = clique_genes,
      Species = clique_species
      ))

      
    }
  }

  
}
      


cat("Number of ortholog groups with at least one expressolog: ", length(unique(angio_spec_OG)),"\n","Number of ortholog groups with at least one fully sized clique: ",length(unique(max_clique_ortholog_groups)))


```


## Filtering expressologs by p-value and creating df with clade member counts


```{r}

# # Set p-value threshold
p_thr <- 0.1

length(unique(max_clique_ortholog_groups))

# Select the ortholog group with highest clique score
max_clique_group_sum <- expressologs_from_max_cliques %>% 
  mutate(species_pair = paste0(Species1, Species2)) %>%  
  group_by(OrthologGroup) %>% 
  arrange(cliqueSum) %>% 
  slice(1:3) %>% 
  ungroup() 
  
length(unique(max_clique_group_sum$OrthologGroup))

speciesPairs <- tibble(SpeciesPair = max_clique_group_sum %>% distinct(species_pair) %>% pull(species_pair),
                       SpeciesPairClade = c( "Angio","Angio", "Angio"))



max_clique_group_sum <-  left_join(max_clique_group_sum , speciesPairs, by = join_by("species_pair" == "SpeciesPair" ))

# Create a data frame which allows for filtering based on number of members per clique.
max_clique_group_sum <- max_clique_group_sum %>%
  group_by(OrthologGroup, species_pair) %>% 
  arrange(MaxpVal) %>%
  filter(MaxpVal < p_thr) %>% 
  group_by(OrthologGroup) %>% 
  mutate(conservedOG = n()) %>% 
  ungroup() %>% 
  pivot_wider(names_from = SpeciesPairClade, values_from = SpeciesPairClade) 
  
length(unique(max_clique_group_sum$OrthologGroup))

max_clique_group_sum$Angio[is.na(max_clique_group_sum$Angio)] <-0
max_clique_group_sum$Angio[max_clique_group_sum$Angio != 0] <-1

```

## Identifying best clique, and removing duplicated genes


```{r}


ultra_conserved_Angio <- max_clique_group_sum %>%
  mutate_at(c("Angio"), as.numeric) %>%
  filter(conservedOG == 3)

length(unique(ultra_conserved_Angio$OrthologGroup))

# 1) Identify the best clique per orthogroup

uuc_genes_filtered <- uuc_genes %>% 
  filter(Orthogroup %in% ultra_conserved_Angio$OrthologGroup) 

length(unique(uuc_genes_filtered$Orthogroup))


uuc_genes_only_one_clique <- c()

for(i in unique(uuc_genes_filtered$Orthogroup)){
   # i <- "OG0000033"
  print(i)
  
  lowest_scoring_clique <- ultra_conserved_Angio %>% 
    filter(OrthologGroup == i)
  
  filtered_genes <- uuc_genes %>% 
    filter(Orthogroup == i) %>% 
    filter(Genes %in% lowest_scoring_clique$GeneSpecies1 | Genes %in% lowest_scoring_clique$GeneSpecies2) %>% 
    distinct(Genes, .keep_all = T)
  
  uuc_genes_only_one_clique <- rbind(uuc_genes_only_one_clique, filtered_genes)
  
}

# 2) Remove the duplicated genes
uuc_genes_only_one_clique <- uuc_genes_only_one_clique %>% 
  distinct(Genes, .keep_all = T) %>% 
  group_by(Orthogroup) %>% 
  mutate(sum = n()) %>% 
  filter(sum == 3) %>% 
  ungroup()

length(unique(uuc_genes_only_one_clique$Orthogroup))

# 3) Re-filter the conserved ortholog groups to remove orthogroups that had duplicates so to retain only the complete cliques

ultra_conserved_Angio <- ultra_conserved_Angio %>% 
  filter(conservedOG == 3)

# 4) Re-filter the uuc genes that now only contain one clique per orthogroup to also contain only complete cliques.

uuc_genes_only_one_clique <- uuc_genes_only_one_clique %>% 
  filter(Orthogroup %in% ultra_conserved_Angio$OrthologGroup)

length(unique(uuc_genes_only_one_clique$Orthogroup))


# PARTIAL CLIQUES
partial3_conserved_Angio <- max_clique_group_sum %>%
  mutate_at(c("Angio"), as.numeric) %>%
  filter(conservedOG >= 2)

length(unique(partial3_conserved_Angio$OrthologGroup))

# 1) Identify the best clique per orthogroup

part_genes_filtered <- uuc_genes %>% 
  filter(Orthogroup %in% partial3_conserved_Angio$OrthologGroup)



part_genes_only_one_clique <- c()

for(i in unique(part_genes_filtered$Orthogroup)){
   # i <- "OG0000033"
  print(i)
  
  lowest_scoring_clique <- partial3_conserved_Angio %>% 
    filter(OrthologGroup == i)
  
  filtered_genes <- uuc_genes %>% 
    filter(Orthogroup == i) %>% 
    filter(Genes %in% lowest_scoring_clique$GeneSpecies1 | Genes %in% lowest_scoring_clique$GeneSpecies2) %>% 
    distinct(Genes, .keep_all = T)
  
  part_genes_only_one_clique <- rbind(part_genes_only_one_clique, filtered_genes)
  
}

# 2) Remove the duplicated genes
part_genes_only_one_clique <- part_genes_only_one_clique %>% 
  group_by(Species) %>% 
  distinct(Genes, .keep_all = T) %>% 
  group_by(Orthogroup) %>% 
  mutate(sum = n()) %>% 
  filter(sum >= 2) %>% 
  ungroup()



# 3) Re-filter the uuc genes that now only contain one clique per orthogroup to also contain only complete cliques.

part_genes_only_one_clique <- part_genes_only_one_clique %>% 
  filter(Orthogroup %in% partial3_conserved_Angio$OrthologGroup)

length(unique(part_genes_only_one_clique$Orthogroup))

```




```{r eval=FALSE, include=FALSE}
# Saving the uuc-genes - no duplicates

save(uuc_genes_only_one_clique, file = "Data/DATA/uuc_orthologs_angiosperms.RData")

```

```{r eval=FALSE, include=FALSE}
#Saving uuc-genes for only Aspen
uuc_genes_asp <- uuc_genes_only_one_clique %>% 
  filter(grepl("Potra", Genes))

save(uuc_genes_asp, file ="Data/DATA/uuc_orthologs_angiosperms_asp.RData") # Now go to GSEA!

```


