---
title: "Conserved I-graph"
author: "Ellen Dimmen Chapple"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    number_sections: true
    toc_float: true
    theme: lumen
editor_options:
  chunk_output_type: console
---


```{r}

library(tidyverse)
library(ggpattern)
library(RColorBrewer)
library(cowplot)

```

# Plotting of conserved ortholog groups for all groups

Use data from RMD files CONSERVED_IGRAPH_MAIN_ver1.4 + 1.5 + 1.6 and from UPSET_main_ver4 (summary_df)


```{r}

# Across
count_df_across <- data.frame(
  goup = rep("Across", 4),
  set = factor(c("A", "B", "C", "D")),
  conserved = factor(c("Fully", "Partially", "Fully", "Partially")),
  clique = factor(c("No", "No","Yes", "Yes")),
  OrthologGroups = c(1096, 2358, 714, 1278)
)


count_df_across <- count_df_across %>% 
  arrange(conserved) %>% 
  mutate(conserved = factor(conserved, levels =c("Fully", "Partially")))

# Gymno  
count_df_gymno <- data.frame(

  group = rep("Gymnosperm", 4),
  set = factor(c("A", "B", "C", "D")),
  conserved = factor(c("Fully", "Partially", "Fully", "Partially")),
  clique = factor(c("No", "No","Yes", "Yes")),
  OrthologGroups = c(781, 1031, 672, 779)
)



count_df_gymno <- count_df_gymno %>% 
  arrange(conserved) %>% 
  mutate(conserved = factor(conserved, levels =c("Fully", "Partially"))) 

# Angio

count_df_angio <- data.frame(
  group = c(rep("Angiosperm", 4)),
  set = factor(c("A", "B", "C", "D")),
  conserved = factor(c("Fully", "Partially", "Fully", "Partially")),
  clique = factor(c("No", "No","Yes", "Yes")),
  OrthologGroups = c(432, 633, 364, 426)
)



count_df_angio <- count_df_angio %>% 
  arrange(conserved) %>% 
  mutate(conserved = factor(conserved, levels =c("Fully", "Partially"))) 

```



```{r}


# ibm_pal <- c("#3D5A71","#FFB000","#785EF0", "#DC267F","#FE6100")

# palette_1 <- c("#3D5A71", "#DC267F")
palette_1 <- c( "#3182bd","#9ecae1")
fill_col <- "#f7f7f7"
width_1 <- 0.5


plot_across <- ggplot(count_df_across, aes(x = conserved, y = OrthologGroups, fill = conserved)) +
  geom_bar_pattern(aes(pattern = clique),position = "dodge",stat = "identity", width = width_1,
                   colour = "#666666",
                   pattern_angle = 30,
                   pattern_density = 0.08,
                   pattern_spacing = 0.05,
                   pattern_fill = "#666666",
                   pattern_alpha = 0.6,
                   pattern_size = 0.6)  +
  scale_fill_manual(values = palette_1)  +
  scale_pattern_manual(values = c(Yes = "stripe", No = "none")) +
  ylim(0,2500) +  
  theme_minimal() + ggtitle(label = "Across clades") + 
  theme(text = element_text(size = 15),legend.position = "none", plot.title = element_text(hjust = 0.5), axis.text.x = element_blank(), axis.title.x = element_blank(), panel.background = element_rect(fill = fill_col)) + geom_text(aes(label = OrthologGroups, group = clique), position = position_dodge(width = 0.6), vjust = -0.5, size = 4.3, fontface = 2) 


plot_gymno <- ggplot(count_df_gymno, aes(x = conserved, y = OrthologGroups, fill = conserved)) +
  geom_bar_pattern(aes(pattern = clique), position = "dodge",stat = "identity", width = width_1,
                   colour = "#666666",
                   pattern_angle = 30,
                   pattern_density = 0.08,
                   pattern_spacing = 0.05,
                   pattern_fill = "#666666",
                   pattern_alpha = 0.6,
                   pattern_size = 0.6)  +
  scale_fill_manual(values = palette_1)  +
  scale_pattern_manual(values = c(Yes = "stripe", No = "none")) +
  ylim(0,2500) +  
  theme_minimal() +  ggtitle(label = "Gymnosperms") +
  theme(text = element_text(size = 15),legend.position = "none", plot.title = element_text(hjust = 0.5), axis.text.x = element_blank(), axis.title.x = element_blank(), axis.text.y = element_blank(),axis.title.y = element_blank(), panel.background = element_rect(fill = fill_col)) + geom_text(aes(label = OrthologGroups, group = clique), position = position_dodge(width = 0.6), vjust = -0.5, size = 4.3, fontface = 2)




plot_angio <- ggplot(count_df_angio, aes(x = conserved, y = OrthologGroups, fill = conserved)) +  geom_bar_pattern(aes(pattern = clique),position = "dodge",stat = "identity", width = width_1,
                   colour = "#666666",
                   pattern_angle = 30,
                   pattern_density = 0.08,
                   pattern_spacing = 0.05,
                   pattern_fill = "#666666",
                   pattern_alpha = 0.6,
                   pattern_size = 0.6)  +
  scale_fill_manual(values = palette_1)  +
  scale_pattern_manual(values = c(Yes = "stripe", No = "none")) +
  ylim(0,2500) +  
  theme_minimal() + ggtitle(label ="Angiosperms") + 
  geom_text(aes(label = OrthologGroups, group = clique), position = position_dodge(width = 0.6), vjust = -0.7,  size = 4.3, fontface = 2)  +
  theme(text = element_text(size =15),legend.position = "right", plot.title = element_text(hjust = 0.5), axis.text.x = element_blank(), axis.title.x = element_blank(), axis.text.y = element_blank(),axis.title.y = element_blank(),panel.background = element_rect(fill = fill_col)) + 
  guides(pattern = guide_legend(order = 2, override.aes = list(fill = fill_col), title = "Clique",title.theme = element_text(size = 15, face = "bold")),
         fill = guide_legend(override.aes = list(pattern = "none"),order = 1, title = "Conserved", title.theme = element_text(size = 15, face = "bold")),
         linetype = guide_legend(title = " ",title.theme = element_text(size = 15, face = "bold")))

```


```{r}
plot_grid(plot_across, plot_gymno, plot_angio,  ncol = 3, rel_widths = c(1,1,1.2))
  
```


