---
title: "Comparative heatmap_"
author: "Ellen Dimmen Chapple"
date: "2023-08-25"
output: 
  html_document:
    code_folding: hide
    toc: true
    number_sections: true
    toc_float: true
    theme: paper
editor_options:
  chunk_output_type: console
---


```{r Packages, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ComplexHeatmap)
library(tibble)
library(cowplot)
library(gplots)
library(gdata)
library(circlize)
library(ape)
library(ggtree)
setwd("~/NMBU/M60-BIAS/EvoTree/githubEvoTree/Comparative-heatmap_files")

```



```{r name list}

species_list <- c("Lodge", "Asp", "Nor","Scots","Birch","Cher")
#"Asp", "Nor", ,  "Cher"
combo <- data.frame(t(combn(species_list, 2)))

```



```{r file names}

# List of file names.

file_list_1 <- c()
for (i in 1:nrow(combo)){
  
  s1 <- combo[i, "X1"]
  s2 <- combo[i, "X2"]
  
  file_name <- paste0("Data/DATA/comparison-",s1,"_",s2,"-pearsonMR0.03no-table.RData")
  file_list_1 <- append(file_list_1, file_name, after = length(file_list_1))
    
}


file_list_2 <- c()
for (i in species_list){
  
  expr_name <- paste0("Data/DATA/",i,"Wood_transcriptomics.txt")
  file_list_2 <- append(file_list_2, expr_name, after = length(file_list_2))
    
}


```

```{r tests not for use, eval=FALSE, include=FALSE}

for (file in file_list) {
  
  if (file.exists(file)) {
  
  print(TRUE)
  
 
  }
  else {
    print(FALSE)
  }  
}

x <- c("London, UK", "Paris, France", "New York, USA")
key <- sapply(strsplit(x, ","), "[",1)

for (file in file_list){
  
  key <- sapply(strsplit(file, "_"), "[",2)
  key <- sapply(strsplit(key, "-"), "[",1)
  name <- paste0("species ", key)

}

a <- "Asp"
b <- "Nor"

test <- c(1:5)
an <- as.character(paste0("hm-",a, "-",b))


mv("test", an)

new_test <- test
tracemem(new_test)

# Create Vector using c()
id <- c(10,11,12,13)

# Copy to a new variable
new_id <- id
tracemem(new_test)

# Remove old variable
rm(id)
tracemem(new_id)




```

This chunk creates the correlation matrices and heatmap in one loop - hm will have one legend. Vertical, not ordered. 

```{r same corr scale, eval=FALSE, include=FALSE}

for (x in file_list_1){ # Go through elements in list containing COMPARISON TABLES.
  if (file.exists(x)){ # If there exists such a list... do all below! Ex. 'Asp-Nor'.
    # This is for BOTH species.
    load(x) # Load file and create a comparison table for the two species.
    p_val <- comparison_table%>%
  # ungroup() %>%
    select(Species1, Species2,OrthoGroup, Max.p.val) %>%
    mutate_at("Max.p.val", as.numeric) %>%
    group_by(OrthoGroup) %>%
    filter(Max.p.val<= 0.05) %>% # only p-values under 0.05
#arrange(Max.p.val,.by_group = T) %>%
# slice(1) %>%
    ungroup() %>%
    distinct(Species1, .keep_all = T) %>%
    distinct( Species2, .keep_all = T)

    p_val_copy <- p_val # Copy the comparison table so it can be used for species 2.

    # This is for SPECIES 1
    key_word_s1 <- sapply(strsplit(x, "_"), "[",1) # Split the comparison file name...
    key_word_s1 <- sapply(strsplit(key_word_s1, "-"), "[",2) # ... keeping the first species name.


    for (i in file_list_2){ # Go through the EXPRESSION DATA.
      if (grepl(key_word_s1, i)){ # If the string above contains key_word_1 ...
      expr_data <- read.delim(i) # ... read the table.

      s1_fs <- p_val %>% # Modify the p_val that was created above.
      left_join(expr_data, join_by(Species1 == Genes)) %>%
      select(-c("Species2", "Max.p.val", "OrthoGroup")) %>%
      as_tibble() %>%
      column_to_rownames(var = "Species1") %>%
      select(contains("1."))
      }}
    
    # This is for SPECIES 2
    key_word_s2 <- sapply(strsplit(x, "_"), "[",2)
    key_word_s2 <- sapply(strsplit(key_word_s2, "-"), "[",1) # Creating key words by keeping the second species name.

    for (i in file_list_2){ # Go through the EXPRESSION DATA...again.
      if (grepl(key_word_s2, i)){ # If the string above contains key_word_2 ...
      expr_data <- read.delim(i) # ... read the table.

      s2_fs <- p_val %>% # Modify the p_val that was created above.
      left_join(expr_data, join_by(Species2 == Genes)) %>%
      select(-c("Species1", "Max.p.val", "OrthoGroup")) %>%
      as_tibble() %>%
      column_to_rownames(var = "Species2") %>%
      select(contains("1."))
  }}

    corr_matrix <- round(cor(s1_fs,s2_fs, method = "pearson"), 4) # Correlation matrix using the filtered + sorted                                                                      expression data for species 1 and 2.
   # !!! Need only one legend for correlation!!!
    # look here! https://github.com/jokergoo/ComplexHeatmap/issues/391
    col_function <- colorRamp2(c(0.2, 0.4, 0.8), c("blue", "white", "red"))
    
    if(key_word_s2== "Nor"){
      hm <-  Heatmap(corr_matrix,
        show_column_names = FALSE, show_row_names = FALSE,
        column_title_gp = gpar(fontsize = 15),
        row_names_gp = gpar(fontsize = 8),
        column_names_gp = gpar(fontsize = 8),
        width = ncol(corr_matrix)*unit(5, "mm"),
        height = nrow(corr_matrix)*unit(5, "mm"),
        row_order = 1:ncol(s1_fs),
        column_order = 1:ncol(s2_fs), col = col_function, 
        heatmap_legend_param = list(
          title = "Corr",
          legend_height = unit(10, "cm"),
          legend_width = unit(6, "cm")
         )) 
            # ,col = col_fun
      
    } else{
    hm <-  Heatmap(corr_matrix, show_column_names = FALSE, show_row_names = FALSE,
    column_title_gp = gpar(fontsize = 15),
    row_names_gp = gpar(fontsize = 8),
    column_names_gp = gpar(fontsize = 8),
    width = ncol(corr_matrix)*unit(5, "mm"),
    height = nrow(corr_matrix)*unit(5, "mm"),
    row_order = 1:ncol(s1_fs),
    column_order = 1:ncol(s2_fs), col = col_function, show_heatmap_legend = FALSE)
    }
 
    new_name <- as.character(paste0("hm-",key_word_s1, "-",key_word_s2))
    mv("hm", new_name) # rename the heatmaps for plotting in grid.
    
    
    
} 
  
  
}


```

```{r convert to grob}

g1 <- grid.grabExpr(print(`hm-Asp-Birch`)) #
g2 <- grid.grabExpr(print(`hm-Asp-Cher`)) #
g3 <- grid.grabExpr(print(`hm-Birch-Cher`)) #
g4 <- grid.grabExpr(print(`hm-Asp-Nor`)) #
g5 <- grid.grabExpr(print(`hm-Nor-Birch`)) 
g6 <- grid.grabExpr(print(`hm-Nor-Cher`))
g7 <- grid.grabExpr(print(`hm-Asp-Scots`)) #
g8 <- grid.grabExpr(print(`hm-Scots-Birch`))
g9 <- grid.grabExpr(print(`hm-Scots-Cher`))
g10 <- grid.grabExpr(print(`hm-Nor-Scots`))  
g11 <- grid.grabExpr(print(`hm-Lodge-Asp`))
g12 <- grid.grabExpr(print(`hm-Lodge-Birch`))
g13 <- grid.grabExpr(print(`hm-Lodge-Cher`))
g14 <- grid.grabExpr(print(`hm-Lodge-Nor`))
g15 <- grid.grabExpr(print(`hm-Lodge-Scots`))
```


```{r fig.height=30, fig.width=30}

# All rows, 30x30
# Grid is 6x6

# Horizontal main
plot_grid(g13, g12, g10, g14, g11, NULL,
          g2, g1, g7, g4, NULL, NULL,
          g6, g5, g13, NULL, NULL, NULL,
          g8, g9, NULL, NULL, NULL,NULL,
          g3, NULL, NULL, NULL, NULL, NULL,
          ncol = 6, nrow = 6)


```

---------------------------------------------------------------------------------------------------------------------

This gives only one name on each side

```{r heatmap as own loop, eval=FALSE, include=FALSE}

for (x in file_list_1){
  if (file.exists(x)){ # If there exists such a list... do all below! Ex. 'Asp-Nor'.
    # This is for BOTH species.
    load(x) # Load file and create a comparison table for the two species.
    p_val <- comparison_table%>%
  # ungroup() %>%
    select(Species1, Species2,OrthoGroup, Max.p.val) %>%
    mutate_at("Max.p.val", as.numeric) %>%
    group_by(OrthoGroup) %>%
    filter(Max.p.val<= 0.05) %>% # only p-values under 0.05
#arrange(Max.p.val,.by_group = T) %>%
# slice(1) %>%
    ungroup() %>%
    distinct(Species1, .keep_all = T) %>%
    distinct( Species2, .keep_all = T)

    p_val_copy <- p_val # Copy the comparison table so it can be used for species 2.

    # This is for SPECIES 1
    key_word_s1 <- sapply(strsplit(x, "_"), "[",1) # Split the comparison file name...
    key_word_s1 <- sapply(strsplit(key_word_s1, "-"), "[",2) # ... keeping the first species name.


    for (i in file_list_2){ # Go through the EXPRESSION DATA.
      if (grepl(key_word_s1, i)){ # If the string above contains key_word_1 ...
      expr_data <- read.delim(i) # ... read the table.

      s1_fs <- p_val %>% # Modify the p_val that was created above.
      left_join(expr_data, join_by(Species1 == Genes)) %>%
      select(-c("Species2", "Max.p.val", "OrthoGroup")) %>%
      as_tibble() %>%
      column_to_rownames(var = "Species1") %>%
      select(contains("1."))
      }}
    
    
    # This is for SPECIES 2
    key_word_s2 <- sapply(strsplit(x, "_"), "[",2)
    key_word_s2 <- sapply(strsplit(key_word_s2, "-"), "[",1) # Creating key words by keeping the second species name.

    for (i in file_list_2){ # Go through the EXPRESSION DATA...again.
      if (grepl(key_word_s2, i)){ # If the string above contains key_word_2 ...
      expr_data <- read.delim(i) # ... read the table.

      s2_fs <- p_val %>% # Modify the p_val that was created above.
      left_join(expr_data, join_by(Species2 == Genes)) %>%
      select(-c("Species1", "Max.p.val", "OrthoGroup")) %>%
      as_tibble() %>%
      column_to_rownames(var = "Species2") %>%
      select(contains("1."))
  }}

    corr_matrix <- round(cor(s1_fs,s2_fs, method = "pearson"), 4) # Correlation matrix using the filtered + sorted
    new_name <- as.character(paste0("corr_",key_word_s1, "-",key_word_s2))
    mv("corr_matrix", new_name) 
    }
  }

# ------------------ HEATMAP ---------------------------------  

col_function <- colorRamp2(c(0.2, 0.4, 0.8), c("blue", "white", "red"))

corr_list <- c()
for (i in 1:nrow(combo)){
  
  first_s <- combo[i, "X1"]
  second_s <- combo[i, "X2"]
  
  i <- paste0("corr_",first_s,"-",second_s)
  corr_list <- append(corr_list, i, after = length(corr_list))
    
}

# Row 1

for(matrix in corr_list){

    key_word_s1 <- sapply(strsplit(matrix, "_"), "[",2)
    key_word_s1 <- sapply(strsplit(key_word_s1, "-"), "[",1)
    key_word_s2 <- sapply(strsplit(matrix, "-"), "[",2)

    print(matrix)

if(key_word_s1 == "Asp"){  
  if (matrix == "corr_Asp-Cher"){
        hm <-  Heatmap(get(matrix),
        show_column_names = FALSE, show_row_names = FALSE,
        width = ncol(get(matrix))*unit(5, "mm"),
        height = nrow(get(matrix))*unit(5, "mm"),
        row_order = 1:nrow(get(matrix)),
        column_order = 1:ncol(get(matrix)), col = col_function,
        row_title = key_word_s1, column_title = key_word_s2, show_heatmap_legend = F)
        
        print(hm)
        new_name <- as.character(paste0("hm-",key_word_s1, "-",key_word_s2))
        mv("hm", new_name) 
  }
    
  if(matrix =="corr_Asp-Nor"){
    
        hm <-  Heatmap(get(matrix),
        show_column_names = FALSE, show_row_names = FALSE,
        width = ncol(get(matrix))*unit(5, "mm"),
        height = nrow(get(matrix))*unit(5, "mm"),
        row_order = 1:nrow(get(matrix)),
        column_order = 1:ncol(get(matrix)), col = col_function,
        column_title = key_word_s2, 
        heatmap_legend_param = list(
          title = "Corr",
          legend_height = unit(10, "cm"),
          legend_width = unit(6, "cm")))
        
      print(hm)
      new_name <- as.character(paste0("hm-",key_word_s1, "-",key_word_s2))
      mv("hm", new_name)
  }
  
  } 
    #     hm <-  Heatmap(get(matrix),
    #     show_column_names = FALSE, show_row_names = FALSE,
    #     width = ncol(get(matrix))*unit(5, "mm"),
    #     height = nrow(get(matrix))*unit(5, "mm"),
    #     row_order = 1:nrow(get(matrix)),
    #     column_order = 1:ncol(get(matrix)), col = col_function,
    #     column_title = key_word_s2, show_heatmap_legend = F)
    #     
    #  
    #     new_name <- as.character(paste0("hm-",key_word_s1, "-",key_word_s2))
    #     mv("hm", new_name)
    #   

}

for(matrix in corr_list){

    key_word_s1 <- sapply(strsplit(matrix, "_"), "[",2)
    key_word_s1 <- sapply(strsplit(key_word_s1, "-"), "[",1)
    key_word_s2 <- sapply(strsplit(matrix, "-"), "[",2)

    print(matrix)
    
    

  if(matrix== "Cher"){

      hm <-  Heatmap(get(matrix),
        show_column_names = FALSE, show_row_names = FALSE,
        width = ncol(get(matrix))*unit(5, "mm"),
        height = nrow(get(matrix))*unit(5, "mm"),
        row_order = 1:nrow(get(matrix)),
        column_order = 1:ncol(get(matrix)), col = col_function,
        row_title = key_word_s1)
      hm  
      new_name <- as.character(paste0("hm-",key_word_s1, "-",key_word_s2))
      mv("hm", new_name)
    }}
 
  
    
    

    else{
    hm <-  Heatmap(get(matrix), 
      show_column_names = FALSE, show_row_names = FALSE,
        width = ncol(get(matrix))*unit(5, "mm"),
        height = nrow(get(matrix))*unit(5, "mm"),
        row_order = 1:nrow(get(matrix)),
        column_order = 1:ncol(get(matrix)),col = col_function, show_heatmap_legend = FALSE)
      
    new_name <- as.character(paste0("hm-",key_word_s1, "-",key_word_s2))
      mv("hm", new_name)
  }
    
    
    
 } 




```










